
# Site settings
title: Digital Portal - Sendil Kumar
email: 
description: > # this means to ignore newlines until "baseurl:"
# Digital portal for my personal blogs and posts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.sendildevar.in" # the base hostname & protocol for your site

twitter: iamssk
twitter_username: iamssk
github_username:  wiless

collections:
  articles:
    output: true
  tutorial:
    output: true
  recentposts:
    output: true
  apps:
    output: true

exclude:
  - bower_components
  - Gemfile
  

plugins:
 - jekyll-feed
 - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM  #Github Flavored Markdown
  extensions: [footnotes]
